# Generated by Django 6.0.4 on 2026-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_order_comment_order_delivery_method_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('paid', 'Оплачено'), ('failed', 'Помилка')], default='pending', max_length=20),
        ),
    ]
