# Generated by Django 6.0.4 on 2026-05-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_order_delivery_branch_order_delivery_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'Оформлено'), ('shipped', 'Відправлено'), ('received', 'Отримано')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати')], default='pending', max_length=20),
        ),
    ]
